import Head from "next/head";
import Header from "@/components/Layout/Header";
import Image from "next/image";
import Why from "@/components/Home/Why";
import Recent from "@/components/Home/Recent";
import Testinominal from "@/components/Home/Testinominal";
import Footer from "@/components/Layout/Footer";
import { Project, Service } from "@/types";
import Hero from "@/components/UI/Hero";
import Services from "@/components/Home/Services/Services";

interface Props {
  projects: Project[];
  services: Service[];
}
export default function Home(props: Props) {
  const { projects, services } = props;

  return (
    <>
      <Header />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pb-3"></div>
      <Hero />

      <section className="grid bg-white md:grid-cols-8 items-center px-4   md:px-16  ">
        <div className="col-span-6 ">
          <h3
            className={` md:text-2xl  font-isidorasans font-medium my-4 md:mb-8 text-brand-blue `}
          >
            LONG-TERM ASSET PROTECTION
          </h3>
          <p
            className={`md:text-xl font-isidorasans_regular    text-black md:text-gray-400 `}
          >
            Melbourne Painters has a scheduled and systematic approach in
            providing <br /> preventive and proactive maintenance.
          </p>
        </div>
        <div className="col-span-2 flex items-center">
          <Image
            src="/imgs/Painters-Melbourne-Accredited-Painter-512px-300x300.jpg"
            width={400}
            height={300}
            alt=""
          />
          <Image
            src="/imgs/warranty.png"
            width={100}
            style={{ objectFit: "contain" }}
            height={50}
            alt=""
          />
        </div>
      </section>

      <Services data={services} />
      <Recent data={projects} />

      <Why />
      <Recent data={projects} />
      <Testinominal />
      <Footer />
    </>
  );
}
export const getStaticProps = async () => {
  const url = process.env.NEXT_WP_API_URL + `/projects`;
  const services_url = process.env.NEXT_WP_API_URL + `/service`;
  const projects = await fetch(url).then((r) => r.json());
  const services = await fetch(services_url).then((r) => r.json());

  return {
    props: {
      projects,
      services,
    },
  };
};
